# Generated by Django 5.0.6 on 2024-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_skills_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="images/profiles/user-default.png",
                null=True,
                upload_to="images/profiles/",
            ),
        ),
    ]
