# Generated by Django 5.0.6 on 2024-05-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_rename_value_review_vote_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="images/user-default.png", null=True, upload_to=""
            ),
        ),
    ]
