# Generated by Django 5.0.6 on 2024-05-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="images/default.jpg", null=True, upload_to=""
            ),
        ),
    ]
