# Generated by Django 5.0.6 on 2024-05-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                default="images/default/project-default.png",
                null=True,
                upload_to="images/projects/",
            ),
        ),
    ]
