# Generated by Django 5.0.6 on 2024-05-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_review_owner_alter_project_tags_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="ownser",
            new_name="owner",
        ),
    ]
