# Generated by Django 5.0.6 on 2024-05-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_rename_ownser_project_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-votes", "-vote_ratio", "title"]},
        ),
    ]
